var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/knowledge/yoga-foundation/practice/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__350ea971._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_4b0e09cc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c3300314._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_f72dcf29._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_knowledge_layout_tsx_57fd6a5e._.js")
R.c("server/chunks/ssr/ce889_server_app_knowledge_yoga-foundation_practice_page_actions_889c8044.js")
R.m(46261)
module.exports=R.m(46261).exports
