var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/courses/sanskrit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3f121500._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_96c3abd3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c3300314._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_f72dcf29._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_courses_layout_tsx_a8efb0ea._.js")
R.c("server/chunks/ssr/_next-internal_server_app_courses_sanskrit_page_actions_f42576cd.js")
R.m(99732)
module.exports=R.m(99732).exports
