var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/courses/ashtanga/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__06fcf5a5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_3838860d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c3300314._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_f72dcf29._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_courses_layout_tsx_a8efb0ea._.js")
R.c("server/chunks/ssr/_next-internal_server_app_courses_ashtanga_page_actions_351f1b74.js")
R.m(44701)
module.exports=R.m(44701).exports
